### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by KasibhatlaMidhun** [zero-to-mastery/javascript20-projects#284]
[https://github.com/KasibhatlaMidhun/quotegenerator](url)

**Comment by KasibhatlaMidhun** [comment]
This is my Github repo of the same project

**Comment by hasancbngl** [comment]
If you want to contribute and share your projects check the read me. If you don't know how to do that check contributing guidelines or here that guide can help you to learn:
https://github.com/firstcontributions/first-contributions
